blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
  #post_views
  path('',views.post_list , name  = 'post_list'),
  #path('',views.Postlistview.as_view() , name = 'post_list'),
  path('<int:year>/<int:month>/<int:day>/<slug:post>/' , views.post_detail , name='post_detail'),
  path('<int:post_id>/share/',views.post_share, name = 'post_share'),
  path('tag/<slug:tag_slug>/',views.post_list,name='post_list_by_tag'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
  'posts' : PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self) -> QuerySet:
      return super().get_queryset()\
        .filter(status=Post.Status.PUBLISHED)
    

class Post(models.Model):
  tags = TaggableManager()

  class Status(models.TextChoices):
    DRAFT = 'DF' , 'draft'
    PUBLISHED = 'PB' , 'published'

  

  title = models.CharField(max_length = 100)
  slug = models.SlugField(max_length = 200, unique_for_date = 'publish')
  author = models.ForeignKey(User,on_delete = models.CASCADE,related_name = 'blog_posts')
  body = models.TextField()
  publish = models.DateTimeField(default = timezone.now)
  created = models.DateTimeField(auto_now_add = True)
  updated = models.DateTimeField(auto_now = True)
  status = models.CharField(max_length = 2 , choices = Status.choices , default = Status.DRAFT )
  objects = models.Manager()
  published = PublishedManager()
  

  class meta:
    ordering = ['-publish']
    indexes = [
      models.Index(fields=['-publish']),
    ]

  def __str__(self) -> str:
    return self.title
  
  def get_absolute_url(self):
    return reverse('blog:post_detail', args=[self.publish.year,
                                             self.publish.month,
                                             self.publish.day,
                                             self.slug])

blog/forms.py
from django import forms

class EmailPostForm(forms.Form):
  name = forms.CharField(max_length=50)
  email = forms.EmailField()
  to = forms.EmailField()
  comment = forms.CharField(required= False , widget = forms.Textarea)

blog/views.py
from django.shortcuts import render , get_object_or_404 
from .models import Post
from django.http import Http404 , HttpResponse
from django.core.paginator import Paginator , EmptyPage , PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
# Create your views here.

def post_list(request, tag_slug = None):
  post_list = Post.published.all()

  tag = None
  if tag_slug:
    tag = get_object_or_404(Tag, slug = tag_slug)
    post_list = post_list.filter(tags__in=[tag])


  #nno of post in one page is 3
  paginator = Paginator(post_list, 3)
  page_number = request.GET.get('page', 1)
  try:
    posts = paginator.page(page_number)
  except PageNotAnInteger:
    posts = paginator.page(1)
  except EmptyPage:
    posts = paginator.page(paginator.num_pages)
  return render(request , 'blog/post/list.html', {'posts': posts,'tag':tag})


def post_share(request , post_id):
  post = get_object_or_404(Post, id = post_id , status = Post.Status.PUBLISHED)
  sent = False

  if request.method == 'POST':
    form = EmailPostForm(request.POST)
    if form.is_valid():
      cd = form.cleaned_data
      post_url = request.build_absolute_uri(post.get_absolute_url())
      subject = f"{cd['name']} recommends you read " f"{post.title}"
      message = f"Read {post.title} at {post_url}\n\n"\
                 f"{cd['name']}\'s comments: {cd['comment']}"
      send_mail(subject, message, 'marafay2610@gmail.com',[cd['to']])
      sent = True
  else:
      form = EmailPostForm()
  return render(request , 'blog/post/share.html' , {'post':post,'form':form,'sent':sent})


'''class Postlistview(ListView):
  queryset = Post.published.all()
  context_object_name = 'posts'
  paginate_by = 3
  template_name = 'blog/post/list.html','''


def post_detail(request, month, year, day, post):
  post = get_object_or_404(Post,
                           status = Post.Status.PUBLISHED,
                           slug = post,
                           publish__year = year,
                           publish__month = month,
                           publish__day = day)
  post_tags_ids = post.tags.values_list('id', flat=True)
  similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                .exclude(id=post.id)
  similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                              .order_by('-same_tags','-publish')[:4]
  return render (request , 'blog/post/detail.html' , {'post':post,'similar_posts': similar_posts})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href='{% static "css/blog.css" %}' rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>My blog</h2>
    <p>
      This is my blog.
      </p>
  </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
  <p>
    <a href="{% url 'blog:post_share' post.id %}">
      Share this post
    </a>
  </p>
  <h2>Similar posts</h2>
  {% for post in similar_posts %}
  <p>
  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </p>
  {% empty %}
  There are no similar posts yet.
  {% endfor %}

{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
  <h1>My Blog</h1>
  {% if tag %}
    <h2>
      posts tagged with "{{ tag.name }}"
    </h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="tags">
      Tags:
      {% for tag in post.tags.all %}
      <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
          {{tag.name}}
      </a>  
      {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
{% else %}
  <h1>Share "{{ post.title }}" by e-mail</h1>
  <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
      </form>
    {% endif %}
  {% endblock %}

blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
  {% if page.has_previous %}
  <a href="?page={{ page.previous_page_number }}">Previous</a>
  {% endif %}
  <span class="current">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
    </div>